CREATE TABLE EQUIPAMENTOS(
    NOME NVARCHAR(50) NOT NULL,
    PRECO_AQUISICAO FLOAT NOT NULL,
    NUMERO_SERIE INT NOT NULL,
    DATA_FABRICACAO DATE NOT NULL,
    FABRICANTE NVARCHAR(50) NOT NULL,
	CONSTRAINT PK_EQUIPAMENTOS PRIMARY KEY (NUMERO_SERIE),
);

CREATE TABLE CHAMADOS(
    ID INT IDENTITY(1,1),
    TITULO NVARCHAR(50) NOT NULL,
    DESCRICAO NVARCHAR(200) NOT NULL,
    EQUIPAMENTO_ID INT NOT NULL,
    DATA_ABERTURA DATETIME NOT NULL,
    CONSTRAINT PK_CHAMADOS PRIMARY KEY (ID),
	CONSTRAINT FK_EQUIPAMENTOS FOREIGN KEY (EQUIPAMENTO_ID) REFERENCES Equipamentos(NUMERO_SERIE),
	)
